[package]
name = "trampoline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "byondcore"
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0"
