labelPRBasedOnFilePath:
  Client:
    - OpenDreamClient/**/*
    - OpenDreamShared/**/*
  Runtime:
    - OpenDreamRuntime/**/*
    - OpenDreamServer/**/*
    - OpenDreamShared/**/*
  Compiler:
    - OpenDreamCompiler/**/*
    - DMDissasembler/**/*