labelPRBasedOnFilePath:
  Client:
    - OpenDreamClient/**/*
    - OpenDreamShared/**/*
  Runtime:
    - OpenDreamRuntime/**/*
    - OpenDreamServer/**/*
    - OpenDreamShared/**/*
  Compiler:
    - DMCompiler/**/*
    - DMDisassembler/**/*