using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace OpenDreamClient.Input.ContextMenu {
    [GenerateTypedNameReferences]
    public sealed partial class ContextMenuPopup : Popup {
        [Dependency] private readonly IEntityManager _entityManager = default!;
        [Dependency] private readonly IUserInterfaceManager _uiManager = default!;

        public ContextMenuPopup() {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
        }

        public void RepopulateEntities(IEnumerable<EntityUid> entities) {
            ContextMenu.RemoveAllChildren();
            foreach (EntityUid entity in entities) {
                ContextMenu.AddChild(new ContextMenuItem(_uiManager, _entityManager, entity));
            }
        }
    }
}
