using OpenDreamClient.Rendering;
using OpenDreamShared.Dream;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace OpenDreamClient.Input.ContextMenu;

[GenerateTypedNameReferences]
internal sealed partial class ContextMenuItem : PanelContainer {
    private static readonly StyleBox HoverStyle = new StyleBoxFlat(Color.Gray);

    public readonly ClientObjectReference Target;

    private readonly ContextMenuPopup _menu;

    public ContextMenuItem(ContextMenuPopup menu, ClientObjectReference target, string name, DreamIcon icon) {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Target = target;
        _menu = menu;

        NameLabel.Margin = new Thickness(2, 0, 4, 0);
        NameLabel.Text = name;

        Icon.Texture = icon.LastRenderedTexture;
    }

    protected override void MouseEntered() {
        base.MouseEntered();

        PanelOverride = HoverStyle;
        _menu.SetActiveItem(this);
    }

    protected override void MouseExited() {
        base.MouseExited();

        PanelOverride = null;
    }
}
