using System.Linq;
using OpenDreamClient.Interface.Controls;
using OpenDreamClient.Rendering;
using OpenDreamShared.Dream;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace OpenDreamClient.Input.ContextMenu;

[GenerateTypedNameReferences]
internal sealed partial class VerbMenuPopup : Popup {
    public delegate void VerbSelectedHandler();

    public VerbSelectedHandler? OnVerbSelected;

    private readonly ClientVerbSystem? _verbSystem;

    private readonly ClientObjectReference _target;

    public VerbMenuPopup(ClientVerbSystem? verbSystem, sbyte seeInvisible, ClientObjectReference target, MetaDataComponent? entityMetaData, DMISpriteComponent? entitySprite) {
        RobustXamlLoader.Load(this);

        _verbSystem = verbSystem;
        _target = target;

        if (verbSystem != null) {
            var sorted = verbSystem.GetExecutableVerbs(_target).Order(VerbNameComparer.OrdinalInstance);

            foreach (var (verbId, verbSrc, verbInfo) in sorted) {
                if (verbInfo.IsHidden(false, seeInvisible))
                    continue;
                if(!verbInfo.ShowInPopupAttribute)
                    continue;

                AddVerb(verbId, verbSrc, verbInfo);
            }
        }
    }

    private void AddVerb(int verbId, ClientObjectReference verbSrc, VerbSystem.VerbInfo verbInfo) {
        var button = new Button {
            Text = verbInfo.Name
        };

        var takesTargetArg = verbInfo.GetTargetType() != null && !verbSrc.Equals(_target);

        button.OnPressed += _ => {
            _verbSystem?.ExecuteVerb(verbSrc, verbId, takesTargetArg ? [_target] : []);
            Close();
            OnVerbSelected?.Invoke();
        };

        VerbMenu.AddChild(button);
    }
}
