using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace OpenDreamClient.Input.ContextMenu {
    [GenerateTypedNameReferences]
    public sealed partial class VerbMenuPopup : Popup {
        public VerbMenuPopup(MetaDataComponent? entityMetaData) {
            RobustXamlLoader.Load(this);

            if (entityMetaData != null && !string.IsNullOrEmpty(entityMetaData.EntityDescription)) {
                DescLabel.Margin = new Thickness(4, 0, 4, 0);
                DescLabel.Text = entityMetaData.EntityDescription;
            } else {
                Desc.Visible = false;
            }
        }
    }
}
