/proc/RunTest()
	ASSERT(findtextEx("a𐀀b", "a") == 1)
	ASSERT(findtextEx("a𐀀b", "𐀀") == 2)
	ASSERT(findtextEx("a𐀀b", "b") == 4)
	ASSERT(findtextEx_char("a𐀀b", "a") == 1)
	ASSERT(findtextEx_char("a𐀀b", "𐀀") == 2)
	ASSERT(findtextEx_char("a𐀀b", "b") == 3)
	ASSERT(findtextEx("a𐀀b", "a", 2) == 0)
	ASSERT(findtextEx("a𐀀b", "𐀀", 3) == 0)
	ASSERT(findtextEx("a𐀀b", "b", 1, 2) == 0)
	ASSERT(findtextEx_char("a𐀀b", "a", 2) == 0)
	ASSERT(findtextEx_char("a𐀀b", "𐀀", 3) == 0)
	ASSERT(findtextEx_char("a𐀀b", "b", 1, 2) == 0)
	ASSERT(findtextEx_char("a𐀀b", "b", 1, 3) == 3)
	ASSERT(findtextEx_char("a𐀀b", "a𐀀") == 1)
	ASSERT(findtextEx_char("a𐀀b", "𐀀b") == 2)
	ASSERT(findtextEx_char("a𐀀b", "𐀀bc") == 0)
	ASSERT(findtextEx_char("a𐀀b", "c𐀀b") == 0)
	ASSERT(findtextEx_char("a𐀀b", "a𐀀b") == 1)
	ASSERT(findtextEx_char("aa𐀀𐀀bb", "𐀀𐀀") == 3)
	ASSERT(findtextEx("a𐀀b", "A") == 0)
	ASSERT(findtextEx_char("a𐀀b", "A") == 0)

	// findtext tests
	ASSERT(findtext("a𐀀b", "A") == 1)
	ASSERT(findtext_char("a𐀀b", "A") == 1)
	ASSERT(findtextEx("a𐀀b", "B") == 0)
	ASSERT(findtextEx_char("a𐀀b", "B") == 0)
	ASSERT(findtext("a𐀀b", "B") == 4)
	ASSERT(findtext_char("a𐀀b", "B") == 3)

	// findlasttext tests
	ASSERT(findlasttextEx("aa𐀀𐀀bb", "𐀀") == 5)
	ASSERT(findlasttextEx_char("aa𐀀𐀀bb", "𐀀") == 4)
	ASSERT(findlasttextEx("aa𐀀𐀀bb", "b") == 8)
	ASSERT(findlasttext("aa𐀀𐀀Bb", "B") == 8)
	ASSERT(findlasttextEx("aa𐀀𐀀Bb", "B") == 7)
	ASSERT(findlasttext_char("aa𐀀𐀀Bb", "B") == 6)
	ASSERT(findlasttextEx_char("aa𐀀𐀀Bb", "B") == 5)
	ASSERT(findlasttextEx_char("aa𐀀𐀀bb", "b") == 6)