/proc/RunTest()
	ASSERT(findtext("/mob", "/") == 1)
	ASSERT(findtext("abcdefg", "f", 6) == 6)
	ASSERT(findtext("abcdefg", "f", 7) == 0)
	ASSERT(findtext("Banana", "na") == 3)
	ASSERT(findtext("Banana", "NA") == 3)
	ASSERT(findtext("abcdefg", "f", 1, -1) == 6)
	ASSERT(findtext("abcdefg", "g", 1, -1) == 0)
	ASSERT(findtext("pipe gun", " (Wielded)", -10) == 0)
	ASSERT(findtext("pipe gun", "pipe", -10) == 1)

	ASSERT(findtextEx("Banana", "na") == 3)
	ASSERT(findtextEx("Banana", "NA") == 0)
	ASSERT(findtextEx("abcdefg", "f", 6) == 6)
	ASSERT(findtextEx("abcdefg", "f", 7) == 0)
	ASSERT(findtextEx("pipe gun (Wielded)", "ed", -100) == 16)
	ASSERT(findtextEx("pipe gun (Wielded)", "ed", -100, -1) == 16)
	ASSERT(findtextEx("pipe gun (Wielded)", "ed", -100, -2) == 0)
