/proc/RunTest()
	file("/home/amy/test.txt") << json_encode(findlasttext("abcdefg", "f", 0, -1))	
	ASSERT(findlasttext("abcdefg", "f", 0, -1) == 0)
	file("/home/amy/test.txt") << json_encode(findlasttext("abcdefg", "f", 0, -2))
	ASSERT(findlasttext("abcdefg", "f", 0, -2) == 6)
	file("/home/amy/test.txt") << json_encode(findlasttext("abcdefg", "f", 6))
	ASSERT(findlasttext("abcdefg", "f", 6) == 6)
	file("/home/amy/test.txt") << json_encode(findlasttext("abcdefg", "f", 5))
	ASSERT(findlasttext("abcdefg", "f", 5) == 0)
	file("/home/amy/test.txt") << json_encode(findlasttext("abcdefg", "bc", 2))
	ASSERT(findlasttext("abcdefg", "bc", 2) == 2)
	file("/home/amy/test.txt") << json_encode(findlasttext("abcdefg", "ab", 10))
	ASSERT(findlasttext("abcdefg", "ab", 10) == 1)
	file("/home/amy/test.txt") << json_encode(findlasttext("abcdefg", "f", 5))
	ASSERT(findlasttext("abcdefg", "f", 5) == 0)
	file("/home/amy/test.txt") << json_encode(findlasttext("Banana", "na", -3))
	ASSERT(findlasttext("Banana", "na", -3) == 3)
	file("/home/amy/test.txt") << json_encode(findlasttext("Banana", "na", -5))
	ASSERT(findlasttext("Banana", "na", -5) == 0)
	file("/home/amy/test.txt") << json_encode(findlasttext("Banana", "na", 0))
	ASSERT(findlasttext("Banana", "na", 0) == 5)
	file("/home/amy/test.txt") << json_encode(findlasttext("Banana", "na", 3))
	ASSERT(findlasttext("Banana", "na", 3) == 3)
	file("/home/amy/test.txt") << json_encode(findlasttext("Banana", "na", 2))
	ASSERT(findlasttext("Banana", "na", 2) == 0)
	file("/home/amy/test.txt") << json_encode(findlasttext("Banana", "na", 5))
	ASSERT(findlasttext("Banana", "na", 5) == 5)
	file("/home/amy/test.txt") << json_encode(findlasttext("Banana", "na", 50))
	ASSERT(findlasttext("Banana", "na", 50) == 5)
	file("/home/amy/test.txt") << json_encode(findlasttext("Banana", "na", -50))
	ASSERT(findlasttext("Banana", "na", -50) == 0)
	ASSERT(findlasttext("abcdefg", "f", 6, -50) == 6)
	ASSERT(findlasttext("abcdefg", "f", 6, 50) == 0)

	