/proc/RunTest()
	ASSERT(findlasttext("/mob", "/", 0, 1) == 1)
	ASSERT(findlasttext("/mob", "/") == 1)
	ASSERT(findlasttext("abcdefg", "f", 0, -1) == 0)
	ASSERT(findlasttext("abcdefg", "f", 0, -2) == 6)
	ASSERT(findlasttext("abcdefg", "f", 6) == 6)
	ASSERT(findlasttext("abcdefg", "f", 5) == 0)
	ASSERT(findlasttext("abcdefg", "bc", 2) == 2)
	ASSERT(findlasttext("abcdefg", "ab", 10) == 1)
	ASSERT(findlasttext("abcdefg", "f", 5) == 0)
	ASSERT(findlasttext("Banana", "na", -3) == 3)
	ASSERT(findlasttext("Banana", "na", -5) == 0)
	ASSERT(findlasttext("Banana", "na", 0) == 5)
	ASSERT(findlasttext("Banana", "na", 3) == 3)
	ASSERT(findlasttext("Banana", "na", 2) == 0)
	ASSERT(findlasttext("Banana", "na", 5) == 5)
	ASSERT(findlasttext("Banana", "na", 50) == 5)
	ASSERT(findlasttext("Banana", "na", -50) == 0)
	ASSERT(findlasttext("abcdefg", "f", 6, -50) == 6)
	ASSERT(findlasttext("abcdefg", "f", 6, 50) == 0)

	