using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace OpenDreamClient.InfoLabels;

[GenerateTypedNameReferences]
public sealed partial class InfoLabel : Control {
    public InfoLabel() {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(WipBox, LayoutContainer.LayoutPreset.TopLeft);
        LayoutContainer.SetMarginTop(WipBox, 10);
        LayoutContainer.SetMarginLeft(WipBox, 10);
        LayoutContainer.SetGrowHorizontal(WipBox, LayoutContainer.GrowDirection.End);

#if DEBUG
        DebugWarningLabel.Visible = true;
#endif
    }
}
