/proc/RunTest()
    ASSERT(splicetext("banana", 3, 6, "laclav") == "balaclava")
    ASSERT(splicetext("banana", 1, 6, "laclav") == "laclava")
    ASSERT(splicetext("banana", 3, 0, "laclav") == "balaclav")
    ASSERT(splicetext("abcdef", 3) == "ab")
    ASSERT(splicetext("abcdef", 3, 5) == "abef")
    ASSERT(splicetext("abcdef", 3, 5, null) == "abef")
    ASSERT(splicetext("abcdef", -2, 5, "test") == "abcdtestef")
    ASSERT(splicetext("abcdef", -2, 7, "test") == "abcdtest")
    ASSERT(splicetext("abcdef", 3, -1, "test") == "abtestf")
    ASSERT(splicetext("abcdef", 2, 33, "test") == "atest")
    ASSERT(splicetext("abcdef", 2, -1, "test") == "atestf")
    ASSERT(splicetext(null, 4, 5) == null)
    ASSERT(splicetext("", 4, 5) == "")
    ASSERT(splicetext(null, 4, 5, "test") == "test")
    ASSERT(splicetext("", 4, 5, "test") == "test")
    