name: BYOND unit tests

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - "master"

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add Architecture
        run: |
          sudo dpkg --add-architecture i386
          sudo sed -i'' -E 's/^(deb|deb-src) http:\/\/(azure.archive|security).ubuntu.com/\1 [arch=amd64,i386] http:\/\/\2.ubuntu.com/' /etc/apt/sources.list
          sudo apt-get update

      - name: Install Dependencies
        uses: Eeems-Org/apt-cache-action@v1
        with:
          packages: libssl-dev:i386 libgcc-s1:i386 libcurl4:i386

      - name: Cache BYOND
        uses: actions/cache@v4
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-${{ hashFiles('buildByond.conf')}}
          restore-keys: ${{ runner.os }}-byond

      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd $GITHUB_WORKSPACE
          printenv
          echo "BYOND_SYSTEM=/home/runner/BYOND/byond" >> $GITHUB_ENV
          echo "/home/runner/BYOND/byond/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "MANPATH=/home/runner/BYOND/byond/man:$MANPATH" >> $GITHUB_ENV

      - name: Build Unit Tests
        run: |
          tools/ci/dm.sh Content.IntegrationTests/DMProject/environment.dme

      - name: Run Unit Tests
        run: |
          tools/ci/run_integration_test.sh
