name: Add Extra PR labels

on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  Label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Merge Conflicts
        uses: eps1lon/actions-label-merge-conflict@v3.0.2
        with:
          dirtyLabel: "Merge Conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
      - name: Apply Size Label
        if: (github.event_name == 'pull_request_target' && github.head_ref != 'refs/heads/master')
        uses: pascalgn/size-label-action@v0.5.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"          

